- [Промисы](#промисы)
- [Потребители: then, catch, finally](#потребители-then-catch-finally)
- [then](#then)
- [catch](#catch)
- [finally](#finally)
- [Пример: loadScript](#пример-loadscript)

## Промисы

```javascript
let promise = new Promise (function(resolve, reject) {
    // какой-то скрипт

    // возврат результата
})
```

Промисы принимают параметром функцию, у которой в параметрах две функции:

1. `resolve (value)` - если работа завершилась успешно
2. `reject (new Error("Ошибка"))` - если произошла ошибка, `error` - объект ошибки

Скрипт внутри промиса запускается автоматически, он должен выполнить работу, а затем вызвать `resolve` или `reject`.

У объекта `promise`, возвращаемого конструктором `new Promise`, есть внутренние свойства: 

* `state` (состояние) - вначале `"peding"` ("ожидание), потом меняется на `fulfilled` ("Выполнено успешно") при вызове `resolve` или на `"rejected"` ("Выполнено с ошибкой") при вызове с `reject`.
* `result` ("результат") - вначале `undefined`, далее меняется на `value` при вызове `resolve(value)` или на `error` при вызове `reject(error)`


Функция исполнитель должна вызвать что-то одно: `resolve` или `reject`. Состояние промиса может быть изменено только один раз. 

Все последующие вызовы `resolve` и `reject` будут проигнорированы:

```javascript
let promise = new Promise(function(resolve, reject) {
  resolve("done")

  reject(new Error("…")) // игнорируется
  setTimeout(() => resolve("…")) // игнорируется
})
```
***

## Потребители: then, catch, finally

## then

```javascript
promise.then(
    function (result) // обработает успешное выполнение
    function (error) // обработает ошибку   
)
```

Первый аргумент метода `.then` - функция, которая выполняется, когда промис переходит в состояние <b>"выполнен успешно"</b>, и получает результат.

Второй аргумент `.then` - фукнция, которая выполняется, когда промис переходит в состояние <b>"выполнен с ошибкой"</b>, и получает ошибку.

```javascript
let promise = new Promise(function(resolve, reject) {
  setTimeout(() => resolve("done!"), 1000)
})

// resolve запустит первую функцию, переданную в .then
promise.then(
  result => console.log(result), // выведет "done!" через одну секунду
  error => console.log(error) // не будет запущена
)
```

Если мы заинтересованы только в результате успешного выполнения задачи, то в `then` можно передать только одну функцию: 

```javascript
let promise = new Promise (function(resolve) {
  setTimeout(() => resolve ("done!"), 1000)
})

promise.then(alert) // done!
```
***

## catch

Если нужно обработать ошибку, можно использовать `null` в качестве первого аргумента `then(null, errorHandlingFunction)`. Или можно воспользоваться методом `.catch(errorHandlingFunction)`, который сделает тоже самое.

```javascript
let promise = new Promise((resolve, reject) => {
  setTimeout(() => reject(new Error("Ошибка!")), 1000)
})

// .catch(f) это тоже самое, что promise.then(null, f)
promise.catch(alert) // выведет "Error: Ошибка!" спустя одну секунду
```
***

## finally

Вызов `.finally(f)` похож на `.then(f, f)`, в том смысле, что `f` выполнится в любом случае, когда промис завершится: успешно или с ошибкой.

`finally` хорошо подходит для очистки, например остановки индикатора загрузки, его ведь нужно остановить вне зависимости от результата.

```javascript
new Promise((resolve, reject) => {
  /* сделать что-то, что займёт время, и после вызвать resolve/reject */
})
  // выполнится, когда промис завершится, независимо от того, успешно или нет
  .finally(() => остановить индикатор загрузки)
  .then(result => показать результат, err => показать ошибку)
}
```
***

## Пример: loadScript

Есь функция `loadScript` для загрузки скрипта.

Как выглядит вариант с колбеками:

```javascript
function loadScript (src, callback) {
  const script = document.createElement("script")
  script.src = src

  script.onload = function () {
    callback(null, script)
  }
  script.onerror = function () {
    callback(new Error(`Ошибка загрузки скрипта ${src}`))
  }

  document.head.append(script)
}
```

Теперь перепишем её используя `Promise`.

Новой функции `loadScript` не будет нужен аргумент `callback`. Вместо этого она будет создавать и возвращать объект `Promise`, который будет переходить в состояние "успешно завершён", когда загрузка закончится. Внешний код может добавлять обработчики, используя `.then`.

```javascript
function loadScript(src) {
  return new Promise(function(resolve, reject) {
    let script = document.createElement('script')
    script.src = src

    script.onload = () => resolve(script)
    script.onerror = () => reject(new Error(`Ошибка загрузки скрипта ${src}`))

    document.head.append(script)
  })
}
```

Применение: 

```javascript
const promise = loadScript("https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.11/lodash.js")

promise.then(
  script => alert(`${script.src} загружен!`),
  error => alert(`Ошибка: ${error.message}`)
)

promise.then(script => alert('Ещё один обработчик...'))
```

